export const names = {
    "assignee": "Bearbeiter",
    "comment": "Kommentar",
    "components": "Komponente(n)",
    "created": "Erstellt",
    "creator": "Ersteller",
    "customfield_10002": "Story-Punkte",
    "customfield_10005": "Sprint",
    "description": "Beschreibung",
    "issuelinks": "Verknüpfte Vorgänge",
    "issuetype": "Vorgangstyp",
    "lastViewed": "Zuletzt angezeigt",
    "reporter": "Autor",
    "status": "Status",
    "subtasks": "Unteraufgaben",
    "summary": "Zusammenfassung",
    "updated": "Aktualisiert",
}
